
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: stg_users_table
    description: "A staging table for users"
    columns:
      - name: user_id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: first_name
      - name: last_name
      - name: email
      - name: phone_number
      - name: created_at_users
        tests: 
          - not_null
      - name: updated_at
      - name: address_id

  - name: stg_addresses_table
    description: "A staging table for addresses"
    columns:
      - name: address_id
        tests:
          - unique
          - not_null
      - name: address
      - name: zipcode
        tests:
          - zipcode_five_digit
        description: "Some zipcodes only had 4 digits"
      - name: state
      - name: country

  - name: stg_events_table
    description: "A staging table for events"
    columns:
      - name: event_id
        tests:
          - unique
          - not_null
      - name: session_id
      - name: user_id
      - name: event_type
      - name: page_url
      - name: product_id
      - name: created_at_events
        tests:
          - not_null

  - name: stg_orders_table
    description: "A staging table for orders"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: promo_id
      - name: user_id
      - name: address_id
      - name: created_at_orders
        tests:
          - not_null
      - name: order_cost
      - name: shipping_cost
      - name: order_total
        tests:
          - positive_values
        description: "There was one order_total that was negative"
      - name: tracking_id
      - name: shipping_service
      - name: estimated_delivery_at
      - name: delivered_at
      - name: status_orders

  - name: stg_order_items_table
    description: "A staging table for orders_items"
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: product_id
      - name: user_id
      - name: quantity

  - name: stg_products_table
    description: "A staging table for products"
    columns:
      - name: product_id
        tests:
          - unique
          - not_null
      - name: name
      - name: price
      - name: quantity
 
  - name: stg_promos_table
    description: "A staging table for promos"
    columns:
      - name: promo_id
        tests:
          - unique
          - not_null
      - name: discount
      - name: status_promo



